name: sub_track
description: Subscription Tracker Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0-beta.5+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # TODO Use official stacked_firebase_auth package
  # stacked_firebase_auth:
  #   path: ./packages/stacked_firebase_auth

  #Fast Development
  velocity_x: ^3.0.0

  # Graphic related
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0+1
  simple_icons: ^4.18.5
  emojis:
    path: ./packages/emojis

  # Helpers
  # modal_bottom_sheet: ^2.0.0
  keyboard_actions: ^3.4.0
  image_picker: ^0.7.4
  uuid: ^3.0.3
  time: ^2.0.0
  dart_date: ^1.1.0-nullsafety.0
  flutter_local_notifications:
    git:
      url: https://github.com/ketanchoyal/flutter_local_notifications.git
      path: flutter_local_notifications/
      ref: ios-swift
  fl_chart: ^0.35.0
  email_validator: ^2.0.1
  animator: ^3.0.0
  settings_ui: ^1.0.0
  logger: ^1.0.0
  url_launcher: ^6.0.3
  dismissible_page:
    # path: ../packages/dismissible_page
    git:
      url: https://github.com/ketanchoyal/Flutter_dismissible_page.git
      ref: null-safety

  #Firebase
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  stacked_firebase_auth:
    git:
        url: https://github.com/ketanchoyal/stacked.git
        path: packages/stacked_firebase_auth

  #Connectivity
  cross_connectivity: ^3.0.2

  #Local Storage
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  #State Management
  stacked: ^2.1.0
  stacked_hooks: ^0.2.0
  stacked_services: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  stacked_generator: ^0.4.1
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/launcher_icons/launcher_icon_android.png"
  image_path_ios: "assets/launcher_icons/launcher_icon_ios.png"
  adaptive_icon_background: "#ffffff"

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/subIcons/
    - assets/appIcons/
    - assets/json/
    - assets/images/3x/
    - assets/launcher_icons/
    # - assets/images/button_icons
    # - assets/images/3x

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
